### ISSUE TITLE
Webpack: Module parse failed: Identifier directly after number

### ISSUE THREAD

**Issue by agostinhodev** [sindresorhus/decamelize-keys#5]
Using Expo web and the `decamelize-keys@2.0.1` I'm getting the following error:

```javascript
index.js:1 ./node_modules/decamelize-keys/index.js 15:40
Module parse failed: Identifier directly after number (15:40)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| });
| 
> const cache = new QuickLru({maxSize: 100_000});
| 
| // Reproduces behavior from `map-obj`.
```
How to solve?

**Comment by sindresorhus** [comment]
This is a problem with the Expo build tool not supporting modern JS syntax. Open an issue on Expo instead.

**Comment by agostinhodev** [comment]
@sindresorhus - Fortunately I found the solution.

I was using `@expo/webpack-config` in version `0.17.2`.
However, Expo published a new version of the package, which is `18.0.1`.
After upgrading to newer version, it works!

As you said, it was an Expo problem!
