### ISSUE TITLE
Support legacy environments by removing _ on the number

### ISSUE THREAD

**Issue by sobrinho** [sindresorhus/decamelize-keys#9]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `decamelize-keys@2.0.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/decamelize-keys/index.js b/node_modules/decamelize-keys/index.js
index 026b161..43ffdc3 100644
--- a/node_modules/decamelize-keys/index.js
+++ b/node_modules/decamelize-keys/index.js
@@ -12,7 +12,7 @@ const has = (array, key) => array.some(element => {
 	return element.test(key);
 });
 
-const cache = new QuickLru({maxSize: 100_000});
+const cache = new QuickLru({maxSize: 100000});
 
 // Reproduces behavior from `map-obj`.
 const isObject = value =>
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by sindresorhus** [comment]
No plans for that.
